### ISSUE TITLE
Zone with more than 1 controller

### ISSUE THREAD

**Issue by twa127** [pihome-shc/pihome#368]
Hi,

What do you think about the option to link more than 1 controller to a single zone. Thinking about switching on a number of lamps all using the same schedule, for example lounge lamps to switch on/off 3 individual lamps with the same voice command or schedule?

**Comment by pihome-shc** [comment]
I m thinking how that is going to work?

**Comment by twa127** [comment]
No idea as yet :-)) just wondered if anyone thought it was worthwhile

**Comment by twa127** [comment]
Some grey matter churn :-)

- New table - zone_controllers, like zone sensors but has controler_id and controler_child_id values currently in zone table
- Drop controler_id and controler_child_id columns from zone table
- Add num_controllers column to zone table
- Zone Add/Edit screen modified to allow entry for more than 1 controller
- Modify boiler.php - no real change to zone processing, change zone controller update process to handle variable number of controllers

Comments please :-)))))

**Comment by pihome-shc** [comment]
i have been thinking about this whole afternoon, i think we are back to [issue 247](https://github.com/pihome-shc/pihome/issues/247#issuecomment-663917830), but on same note what if we can offer some sort of groping on non heating zone?

**Comment by twa127** [comment]
Hi,

Bit of an update

I've created a new table zone_controllers and migrated the controler_id, controler_child_id and zone_id from the existing zone table
![z_cont](https://user-images.githubusercontent.com/46624596/89820712-5a27b700-db45-11ea-8c37-c3b3c52d03f8.JPG)

- You can see I have 2 controller allocated to zone 56, one as a Sonoff, the other is a MySensors relay
- In boiler_php within the main zone processing loop I create an array of zone controllers from the new table.
- Pass the zone controllers array to the $zone_commands array instead of controler_id and zone_controler_child_id
- Process the zone controllers in a loop for the number of controllers for each zone

The above basically works but need to do some work on the transition between off/on and schedule off/on

Comments welcome

**Comment by pihome-shc** [comment]
@twa127 can you share your final table structure ?

**Comment by twa127** [comment]
DROP TABLE IF EXISTS `zone_controllers`;
CREATE TABLE IF NOT EXISTS `zone_controllers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sync` tinyint(4) NOT NULL,
  `purge` tinyint(4) NOT NULL COMMENT 'Mark For Deletion',
  `zone_id` int(11),
  `controler_id` int(11),
  `controler_child_id` int(11),
  PRIMARY KEY (`id`),
  KEY `FK_zone_controllers_nodes` (`controler_id`),
  KEY `FK_zone_controllers_zone` (`zone_id`),
  CONSTRAINT `FK_zone_controllers_nodes` FOREIGN KEY (`controler_id`) REFERENCES `nodes` (`id`),
  CONSTRAINT `FK_zone_controllers_zone` FOREIGN KEY (`zone_id`) REFERENCES `zone` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

I've left controler_id and controler_child_id in the zone table for now but will delete them later

Attached php to create new table and migrate data

[migrate_controller.zip](https://github.com/pihome-shc/pihome/files/5053074/migrate_controller.zip)

**Comment by pihome-shc** [comment]
i m struggling to understand things here, i mean you are trying have one zone with multi controller to switch on multiple things at the same time. but how we are going to manage this while creating zone? 

i would suggest to have option for group any number of things and then assign each zone under that group and in schedule and all other places we will have individual zone and group name appears as zone,  think like group as distribution list. this way we have ability to control individual zone and also in group and we can create, edit and delete without much effort. 

if my brain is processing in good condition then your final version of table structures as following:
```
zone_type
	id
	sync
	purge
	name
	cat
	
zone
	id
	sync
	purge
	status
	index_id
	name
	graph_it
	zone_type_id
	
zone_senosrs
	id
	sync
	purge
	max_c
	max_operation_time
	hysteresis_time
	sp_deadband
	zone_id
	sensors_id
	sensor_child_id

zone_controller
	id
	sync
	purge
	zone_id
	controler_id
	controler_child_id
```

**Comment by twa127** [comment]
table structure is as I proposes, with the exception of max_operation_time which moves to the zone table

In zone add/edit for cat2 zones we have the option to add/edit more than 1 controller

**Comment by pihome-shc** [comment]
Ok i m happy with that approach as well, so understand schedule and other places it will be treated as one zone with multiple controller?

**Comment by twa127** [comment]
yep that was my thinking, was just trying to avoid having to say setup 3 individual schedules to turn on 3 lamps at the same time. But more than happy to consider another approach if you have an alternative idea

**Comment by pihome-shc** [comment]
I m happy with this approach, I wasn’t sure how single zone will have multiple controller, i think we can have plus + icon beside controller field to have option for user to add/edit multiple controller.

**Comment by twa127** [comment]
okay I'll carry on. As a first release how about changing the table structure, update boiler.php and zone.php but keeping the single zone controller until I workout the switching logic ?

**Comment by pihome-shc** [comment]
yes that can work as well.

**Comment by twa127** [comment]
Attached phase1 update, migrate_controller.php will create the new zone_controllers table, migrate the date, drop controler-id, controler_child_id and FK from the zone table, it will also run  migrate_controller_view.sql to update the zone_view. Copy other files to correct locations. Should carry on working as before but now boiler.php can handle more than 1 controller per zone, there is no GUI yet to add extra controllers but you can test by manually adding to the zone_controllers table.

Please let me know what you think

[Zone Controllers Update.zip](https://github.com/pihome-shc/pihome/files/5056875/Zone.Controllers.Update.zip)

**Comment by twa127** [comment]
I've done a bit more work on boiler.php and homelist.php to sort out the cat2 zone switching logic, the flow is now as below. Sill need to modify zone.php to allow for multiple controller ids

![flow6](https://user-images.githubusercontent.com/46624596/90035270-89f7cb80-dcb9-11ea-947f-021495aa8016.jpg)

[controllers.zip](https://github.com/pihome-shc/pihome/files/5063756/controllers.zip)

**Comment by twa127** [comment]
I've still got an issue with boiler.php when it finishes a schedule, it is currently leaving leaving with the zone in manual start mode - working on this

**Comment by pihome-shc** [comment]
@twa127 very detailed process,

**Comment by twa127** [comment]
Just a pity it don't work as it shoule :-)))

**Comment by twa127** [comment]
I now have a cat2 zone switching process which appears to work okay, it allows for

- Manual ON/OFF for all controller associated to a zone
- Zone schedule which sets all controller associated to a zone
- Override for a zone which sets the state of all controller associated to a zone

I'm not sure how to handle the button on the Sonoff itself. The options are to control the state of the controller which has its button pressed or to set the sate of all the controllers associated to the zone. Any suggestions ?

The new process flow chart
![flo3](https://user-images.githubusercontent.com/46624596/90166739-9734b900-dd92-11ea-87b3-eed87fe4f2c8.jpg)

**Comment by twa127** [comment]
Hi,

I'm trying to make zone.php work for multiple controllers, but am struggling with the code, does anyone have any suggestions, this is basically what I want it to look like
![zone1](https://user-images.githubusercontent.com/46624596/90247315-38bd1880-de2e-11ea-8cbe-93d027232c7a.JPG)

I would have more hidden inputs across the page which I would make visible when a value was selected for the preceding one

**Comment by pihome-shc** [comment]
on form: is it because we have edit and add in same file? why not add + sign and keep that in loop? 
here is two example 
https://bootsnipp.com/snippets/ykXa
https://stackoverflow.com/questions/35265094/dynamic-form-field-on-bootstrap

**Comment by twa127** [comment]
No have add and edit in the same file does not make much of a difference, I have been able to place multiple inputs for controller id by using a row construct, looks okay on PC but no good on phone, I've attached what I've done so far, only the controller id and child id fields code work for add zone, I've not fixed the rest of the form yet. It might be better to go with your first example, I'll have a play.
[zone.zip](https://github.com/pihome-shc/pihome/files/5080170/zone.zip)

**Comment by pihome-shc** [comment]
just tested you zone file, there is not option to remove zone as in my examples. also another suggestion would be to go vertical instead of horizontal

**Comment by twa127** [comment]
Hi,

I've now gone with a vertical layout a bit like the example https://bootsnipp.com/snippets/ykXa

I could not get the example to work properly within zone.php, so I've produced something similar. I think it is working okay in zone add mode but have not yet worked on zone edit mode. I've also added another field to the zone_controllers table as 'state' tinyint(4), I've modified the migrate code to add the field but for testing purposes you can just manually add to the table.

I'd be grateful if you could test and let me know how it goes, I'll now work on the zone edit.

[update.zip](https://github.com/pihome-shc/pihome/files/5096721/update.zip)

**Comment by pihome-shc** [comment]
i haven't done migration testing but zone add works, only one observation when i add controller the child id stacked below first child id, any way controller and child id stay together and when adding second controller it expand second controller and child id rather then controller 1 and controller 2 and child id 1 and child id 2. 



![image](https://user-images.githubusercontent.com/33334232/90690073-fc901a80-e268-11ea-8779-1b98c2fc7ee3.png)

**Comment by twa127** [comment]
I'll see what I can do :-)

**Comment by twa127** [comment]
Please give this a try and let me know what you think, edit zone partially works now, you can edit existing zones and add new controllers but deleting does not yet work..

[zone.zip](https://github.com/pihome-shc/pihome/files/5103956/zone.zip)

**Comment by pihome-shc** [comment]
adding zone gives option for + and looks good, but when i go editing any existing zone i dont see + for adding extra zone, 
ps i have made any changes to database from your previous update as my dev system decided to take unplanned holidays :(

**Comment by twa127** [comment]
Attached the latest complete set of files for the multiple controllers change, I've added another field to the zone_controllers table and updated the migration script. 

I think this is now at the serious testing stage, the one outstanding issue is how to manage the manual button on the Sonoff itself, I need to give that some more thought. 

Please give it a try if you get chance.
[update.zip](https://github.com/pihome-shc/pihome/files/5114522/update.zip)

**Comment by pihome-shc** [comment]
if i run migrate controller script on my live database: 
```
root@pihome:/var/www/MySQL_Database# php migrate_controller.php

   _____    _   _    _
  |  __ \  (_) | |  | |
  | |__) |  _  | |__| |   ___    _ __ ___     ___
  |  ___/  | | |  __  |  / _ \  | |_  \_ \   / _ \
  | |      | | | |  | | | (_) | | | | | | | |  __/
  |_|      |_| |_|  |_|  \___/  |_| |_| |_|  \___|

      S M A R T   H E A T I N G   C O N T R O L
****************************************************************
*   PiHome Migration Script Version 0.02 Build Date 31/07/2020 *
*   Last Modified on 31/07/2020                                *
*                                      Have Fun - PiHome.eu    *
****************************************************************
2020-08-24 00:54:15 - PiHome Database Migration Script Started
---------------------------------------------------------------
2020-08-24 00:54:15 - php version 7.3.19-1~deb10u1 looks OK
Make Sure you have correct MySQL/MariaDB credentials as following
Hostname:     localhost
Database:     pihome
User Name:    pihomedbadmin
Password:     pihome2018
2020-08-24 00:54:15 - Testing Connection to MySQL/MariaDB Server.
2020-08-24 00:54:15 - Database Server Connection Successfull
2020-08-24 00:54:15 - Checking if Database Exits
2020-08-24 00:54:15 - Database pihome Found
2020-08-24 00:54:15 - Modifying Zone Table.
2020-08-24 00:54:16 - Zone Table Successfully Modified
2020-08-24 00:54:16 - Importing the data to the zone_controllers Table and Updating the zone Table.
2020-08-24 00:54:16 - Importing Migration SQL View File to Database, This could take few minuts.
MySQL Database Error with Query CREATE VIEW zone_view AS
select zone.status, zone.zone_state, zone.sync, zone.id, zone.index_id, zone.name, ztype.type, ztype.category, zone.graph_it, zs.max_c, max_operation_time, zs.hysteresis_time,
zs.sp_deadband, sid.node_id as sensors_id, zs.sensor_child_id,
ctype.`type` AS controller_type, cid.node_id as controler_id, zc.controler_child_id,
IFNULL(lasts.last_seen, lasts_2.last_seen) as last_seen, IFNULL(msv.ms_version, msv_2.ms_version) as ms_version, IFNULL(skv.sketch_version, skv_2.sketch_version) as sketch_version
from zone
LEFT join zone_sensors zs on zone.id = zs.zone_id
LEFT join zone_controllers zc on zone.id = zc.zone_id
join zone_type ztype on zone.type_id = ztype.id
LEFT join nodes sid on zs.sensor_id = sid.id
join nodes ctype on zc.controler_id = ctype.id
join nodes cid on zc.controler_id = cid.id
LEFT join nodes lasts on zs.sensor_id = lasts.id
LEFT join nodes lasts_2 on zc.controler_id = lasts_2.id
LEFT join nodes msv on zs.sensor_id = msv.id
LEFT join nodes msv_2 on zc.controler_id = msv_2.id
LEFT join nodes skv on zs.sensor_id = skv.id
LEFT join nodes skv_2 on zc.controler_id = skv_2.id
where zone.`purge` = '0';
:Column 'max_operation_time' in field list is ambiguous
2020-08-24 00:54:16 - DataBase Views File /var/www/MySQL_Database/migrate_controller_view.sql Imported Successfully
2020-08-24 00:54:16 - DataBase Updated Successfully
root@pihome:/var/www/MySQL_Database#

``` 
here are the results of updating database:

```
root@pihome:/var/www/MySQL_Database# php update_db.php

   _____    _   _    _
  |  __ \  (_) | |  | |
  | |__) |  _  | |__| |   ___    _ __ ___     ___
  |  ___/  | | |  __  |  / _ \  | |_  \_ \   / _ \
  | |      | | | |  | | | (_) | | | | | | | |  __/
  |_|      |_| |_|  |_|  \___/  |_| |_| |_|  \___|

      S M A R T   H E A T I N G   C O N T R O L
***************************************************************
*   PiHome Datase Script Version 0.02 Build Date 15/09/2019   *
*   Last Modified on 05/04/2020                               *
*                                      Have Fun - PiHome.eu   *
***************************************************************
2020-08-24 00:56:02 - PiHome Database Update Script Started
---------------------------------------------------------------
2020-08-24 00:56:02 - php version 7.3.19-1~deb10u1 looks OK
Make Sure you have correct MySQL/MariaDB credentials as following
Hostname:     localhost
Database:     pihome
User Name:    pihomedbadmin
Password:     pihome2018
2020-08-24 00:56:02 - Testing Connection to MySQL/MariaDB Server.
2020-08-24 00:56:02 - Database Server Connection Successfull
2020-08-24 00:56:02 - Checking if Database Exits
2020-08-24 00:56:02 - Database pihome Found
2020-08-24 00:56:02 - Checking GITHUB for Database Update
2020-08-24 00:56:03 - Database Update Found on GITHUB
2020-08-24 00:56:03 - The Following Updates will be Applied to the Database.
2020-08-24 00:56:03 - ALTER TABLE `add_on_logs` MODIFY `expected_end_date_time` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `add_on_logs` MODIFY `start_cause` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `add_on_logs` MODIFY `start_datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `add_on_logs` MODIFY `stop_cause` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `add_on_logs` MODIFY `stop_datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `add_on_zone_logs` MODIFY `add_on_log_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `add_on_zone_logs` MODIFY `status` int(11);
2020-08-24 00:56:03 - ALTER TABLE `add_on_zone_logs` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `away` MODIFY `away_button_child_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `away` MODIFY `away_button_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `away` MODIFY `end_datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `away` MODIFY `start_datetime` timestamp NULL ON UPDATE current_timestamp();
2020-08-24 00:56:03 - ALTER TABLE `away` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `datetime` timestamp NULL ON UPDATE current_timestamp();
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `fired_status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `hysteresis_time` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `max_operation_time` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `name` char(50) CHARACTER SET utf16 COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `node_child_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `node_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `overrun` SMALLINT(6) NULL DEFAULT NULL;
2020-08-24 00:56:03 - ALTER TABLE `boiler` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boiler_logs` MODIFY `expected_end_date_time` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `boiler_logs` MODIFY `start_cause` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `boiler_logs` MODIFY `start_datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `boiler_logs` MODIFY `stop_cause` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `boiler_logs` MODIFY `stop_datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `boost_button_child_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `boost_button_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `minute` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `temperature` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `time` timestamp NOT NULL ON UPDATE current_timestamp();
2020-08-24 00:56:03 - ALTER TABLE `boost` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `command` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `comments` varchar(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `day` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `hour` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `min` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `month` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `output` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `status` char(50);
2020-08-24 00:56:03 - ALTER TABLE `crontab` MODIFY `weekday` char(50);
2020-08-24 00:56:03 - ALTER TABLE `email` MODIFY `from` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `email` MODIFY `password` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `email` MODIFY `smtp` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `email` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `email` MODIFY `to` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `email` MODIFY `username` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `frost_protection` MODIFY `datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `gateway` MODIFY `find_gw` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `gateway` MODIFY `pid_running_since` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `gateway` MODIFY `pid` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `gateway` MODIFY `reboot` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `gateway` MODIFY `version` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `gateway_logs` MODIFY `location` char(50) COLLATE utf16_bin COMMENT 'ip address or serial port location i.e. /dev/ttyAMA0';
2020-08-24 00:56:03 - ALTER TABLE `gateway_logs` MODIFY `pid_datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `gateway_logs` MODIFY `pid_start_time` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `gateway_logs` MODIFY `pid` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `gateway_logs` MODIFY `port` char(50) COLLATE utf16_bin COMMENT 'port number or baud rate for serial gateway';
2020-08-24 00:56:03 - ALTER TABLE `gateway_logs` MODIFY `type` char(50) COLLATE utf16_bin COMMENT 'serial or wifi';
2020-08-24 00:56:03 - ALTER TABLE `holidays` MODIFY `end_date_time` datetime;
2020-08-24 00:56:03 - ALTER TABLE `holidays` MODIFY `start_date_time` datetime;
2020-08-24 00:56:03 - ALTER TABLE `holidays` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `http_messages` MODIFY `command` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `http_messages` MODIFY `message_type` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `http_messages` MODIFY `node_id` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `http_messages` MODIFY `parameter` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `http_messages` MODIFY `zone_name` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `messages_in` MODIFY `child_id` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `messages_in` MODIFY `datetime` timestamp NOT NULL;
2020-08-24 00:56:03 - ALTER TABLE `messages_in` MODIFY `node_id` char(15) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `messages_in` MODIFY `payload` decimal(10,2);
2020-08-24 00:56:03 - ALTER TABLE `messages_in` MODIFY `sub_type` int(11);
2020-08-24 00:56:03 - ALTER TABLE `messages_out` MODIFY `datetime` timestamp NOT NULL ON UPDATE current_timestamp() COMMENT 'Current datetime';
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `dns1_address` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `dns2_address` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `gateway_address` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `hostname` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `interface_num` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `interface_type` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `ip_address` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `mac_address` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `net_mask` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `network_settings` MODIFY `primary_interface` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `last_seen` timestamp NULL ON UPDATE current_timestamp();
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `min_value` int(11);
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `ms_version` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `name` char(50) CHARACTER SET utf8 COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `repeater` tinyint(4) COMMENT 'Repeater Feature Enabled=1 or Disable=0';
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `sketch_version` char(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `status` char(50) CHARACTER SET utf8 COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `nodes` MODIFY `type` CHAR(50) NOT NULL COLLATE 'utf8_bin';
2020-08-24 00:56:03 - ALTER TABLE `nodes_battery` MODIFY `bat_level` decimal(10,2);
2020-08-24 00:56:03 - ALTER TABLE `nodes_battery` MODIFY `bat_voltage` decimal(10,2);
2020-08-24 00:56:03 - ALTER TABLE `nodes_battery` MODIFY `node_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `nodes_battery` MODIFY `update` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `notice` MODIFY `datetime` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `notice` MODIFY `message` varchar(200) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `notice` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `override` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `override` MODIFY `temperature` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `override` MODIFY `time` timestamp NULL ON UPDATE current_timestamp();
2020-08-24 00:56:03 - ALTER TABLE `override` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time` MODIFY `end` time;
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time` MODIFY `sch_name` varchar(200) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time` MODIFY `start` time;
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time_zone` MODIFY `holidays_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time_zone` MODIFY `schedule_daily_time_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time_zone` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `schedule_daily_time_zone` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `schedule_night_climat_zone` MODIFY `schedule_night_climate_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `schedule_night_climat_zone` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `schedule_night_climat_zone` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `schedule_night_climate_time` MODIFY `end_time` time;
2020-08-24 00:56:03 - ALTER TABLE `schedule_night_climate_time` MODIFY `start_time` time;
2020-08-24 00:56:03 - ALTER TABLE `schedule_night_climate_time` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `backup_email` char(100) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `build` varchar(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `city` char(100) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `country` char(2) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `language` char(10) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `name` varchar(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `openweather_api` char(100) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `ping_home` bit(1);
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `reboot` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `shutdown` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `timezone` varchar(50) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `update_alias` char(100) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `update_file` char(100) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `update_location` char(250) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `version` varchar(50) CHARACTER SET latin1;
2020-08-24 00:56:03 - ALTER TABLE `system` MODIFY `zip` char(100) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `account_date` timestamp NOT NULL;
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `account_enable` tinyint(1);
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `backup` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `cpdate` timestamp NOT NULL ON UPDATE current_timestamp();
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `settings` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `support` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `user` MODIFY `users` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `userhistory` MODIFY `audit` tinytext;
2020-08-24 00:56:03 - ALTER TABLE `userhistory` MODIFY `date` datetime;
2020-08-24 00:56:03 - ALTER TABLE `userhistory` MODIFY `ipaddress` tinytext;
2020-08-24 00:56:03 - ALTER TABLE `userhistory` MODIFY `password` varchar(50);
2020-08-24 00:56:03 - ALTER TABLE `userhistory` MODIFY `username` varchar(50);
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `c` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `description` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `img` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `last_update` timestamp NOT NULL ON UPDATE current_timestamp() COMMENT 'Last weather update';
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `location` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `sunrise` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `sunset` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `title` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `weather` MODIFY `wind_speed` varchar(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `controler_child_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `controler_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `index_id` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `max_operation_time` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `name` char(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `status` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `type_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone` MODIFY `zone_state` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `controler_fault` int(1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `controler_seen_time` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `mode` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `overrun` tinyint(1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `sensor_fault` int(1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `sensor_reading_time` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `sensor_seen_time` timestamp NULL;
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `status` tinyint(1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `temp_cut_in` decimal(4,1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `temp_cut_out` decimal(4,1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `temp_reading` decimal(4,1);
2020-08-24 00:56:03 - ALTER TABLE `zone_current_state` MODIFY `temp_target` decimal(4,1);
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `category` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `child_id` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `datetime` timestamp NOT NULL;
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `name` char(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `node_id` char(15) COLLATE utf16_bin;
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `payload` decimal(10,2);
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `sub_type` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `type` char(50) COLLATE utf8_bin;
2020-08-24 00:56:03 - ALTER TABLE `zone_graphs` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_logs` MODIFY `boiler_log_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_logs` MODIFY `status` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_logs` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_sensors` MODIFY `hysteresis_time` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone_sensors` MODIFY `max_c` tinyint(4);
2020-08-24 00:56:03 - ALTER TABLE `zone_sensors` DROP `max_operation_time`;
2020-08-24 00:56:03 - ALTER TABLE `zone_sensors` MODIFY `sensor_child_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_sensors` MODIFY `sensor_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_sensors` MODIFY `zone_id` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_type` MODIFY `category` int(11);
2020-08-24 00:56:03 - ALTER TABLE `zone_type` MODIFY `type` char(50) COLLATE utf8_bin;
2020-08-24 00:56:03
Existing Database Table Structures will be amended.
Are you sure you want to do this?  Type 'yes' to continue?
---------------------------------------------------------------
yes
2020-08-24 00:56:05 - Creating Dump File for Exiting Database.
2020-08-24 00:56:06 - Compressing Database Dump File pihome_2020-08-24_00-56-05.sql
2020-08-24 00:56:07 - Compressed Database Dump File pihome_2020-08-24_00-56-06.zip
2020-08-24 00:56:07 - Applying Updates to Database.
2020-08-24 00:56:08 - Database Updates Applied
2020-08-24 00:56:08 - Importing SQL Table View File to Database, This could take few minuts.
MySQL Database Error with Query CREATE VIEW zone_view AS
select zone.status, zone.zone_state, zone.sync, zone.id, zone.index_id, zone.name, ztype.type, ztype.category, zone.graph_it, zs.max_c, max_operation_time, zs.hysteresis_time,
zs.sp_deadband, sid.node_id as sensors_id, zs.sensor_child_id,
ctype.`type` AS controller_type, cid.node_id as controler_id, zc.controler_child_id,
IFNULL(lasts.last_seen, lasts_2.last_seen) as last_seen, IFNULL(msv.ms_version, msv_2.ms_version) as ms_version, IFNULL(skv.sketch_version, skv_2.sketch_version) as sketch_version
from zone
LEFT join zone_sensors zs on zone.id = zs.zone_id
LEFT join zone_controllers zc on zone.id = zc.zone_id
join zone_type ztype on zone.type_id = ztype.id
LEFT join nodes sid on zs.sensor_id = sid.id
join nodes ctype on zc.controler_id = ctype.id
join nodes cid on zc.controler_id = cid.id
LEFT join nodes lasts on zs.sensor_id = lasts.id
LEFT join nodes lasts_2 on zc.controler_id = lasts_2.id
LEFT join nodes msv on zs.sensor_id = msv.id
LEFT join nodes msv_2 on zc.controler_id = msv_2.id
LEFT join nodes skv on zs.sensor_id = skv.id
LEFT join nodes skv_2 on zc.controler_id = skv_2.id
where zone.`purge` = '0';
:Table 'pihome.zone_controllers' doesn't exist
2020-08-24 00:56:09 - DataBase File /var/www/MySQL_Database/MySQL_View.sql Imported Successfully
2020-08-24 00:56:09 - Update Version: 1.76
2020-08-24 00:56:09 - Update Build: 020820
2020-08-24 00:56:09 - MySQL Update DataBase Script Ended
****************************************************************************************
root@pihome:/var/www/MySQL_Database#
```
after updating database the migrate controller scripts run ok without any error, it delete controller id and child id from zone table and create zone table but do not migrate controller related info into controller table. i have attached the database as well if you want to experiment 
[pihome_post_migration.zip](https://github.com/pihome-shc/pihome/files/5115208/pihome_post_migration.zip)

```
root@pihome:/var/www/MySQL_Database# php migrate_controller.php

   _____    _   _    _
  |  __ \  (_) | |  | |
  | |__) |  _  | |__| |   ___    _ __ ___     ___
  |  ___/  | | |  __  |  / _ \  | |_  \_ \   / _ \
  | |      | | | |  | | | (_) | | | | | | | |  __/
  |_|      |_| |_|  |_|  \___/  |_| |_| |_|  \___|

      S M A R T   H E A T I N G   C O N T R O L
****************************************************************
*   PiHome Migration Script Version 0.02 Build Date 31/07/2020 *
*   Last Modified on 31/07/2020                                *
*                                      Have Fun - PiHome.eu    *
****************************************************************
2020-08-24 00:57:08 - PiHome Database Migration Script Started
---------------------------------------------------------------
2020-08-24 00:57:08 - php version 7.3.19-1~deb10u1 looks OK
Make Sure you have correct MySQL/MariaDB credentials as following
Hostname:     localhost
Database:     pihome
User Name:    pihomedbadmin
Password:     pihome2018
2020-08-24 00:57:08 - Testing Connection to MySQL/MariaDB Server.
2020-08-24 00:57:08 - Database Server Connection Successfull
2020-08-24 00:57:08 - Checking if Database Exits
2020-08-24 00:57:08 - Database pihome Found
2020-08-24 00:57:08 - Modifying Zone Table.
2020-08-24 00:57:08 - Zone Table Successfully Modified
2020-08-24 00:57:08 - Importing the data to the zone_controllers Table and Updating the zone Table.
2020-08-24 00:57:08 - Importing Migration SQL View File to Database, This could take few minuts.
2020-08-24 00:57:08 - DataBase Views File /var/www/MySQL_Database/migrate_controller_view.sql Imported Successfully
2020-08-24 00:57:08 - DataBase Updated Successfully
````

**Comment by twa127** [comment]
Found the problem - the migration script was expecting the database to have been created with the latest version of migrate_db.php which has the max_operation_time left in the zone table. The attached should now work okay, please let me know.
[migrate_controller.zip](https://github.com/pihome-shc/pihome/files/5117448/migrate_controller.zip)

**Comment by pihome-shc** [comment]
@twa127 i believe my live database is up-to date, is there anything i missed in db update? 
last migrate_controller.php worked as expected. 

```
2020-08-24 22:18:06 - PiHome Database Migration Script Started
---------------------------------------------------------------
2020-08-24 22:18:06 - php version 7.3.19-1~deb10u1 looks OK
Make Sure you have correct MySQL/MariaDB credentials as following
Hostname:     localhost
Database:     pihome
User Name:    pihomedbadmin
Password:     pihome2018
2020-08-24 22:18:06 - Testing Connection to MySQL/MariaDB Server.
2020-08-24 22:18:06 - Database Server Connection Successfull
2020-08-24 22:18:06 - Checking if Database Exits
2020-08-24 22:18:06 - Database pihome Found
2020-08-24 22:18:06 - Modifying Zone Table.
2020-08-24 22:18:07 - Zone Table Successfully Modified
2020-08-24 22:18:07 - Modifying Zone Sensors Table.
2020-08-24 22:18:07 - Zone Sensors Table Successfully Modified
2020-08-24 22:18:07 - Importing the data to the zone_controllers Table and Updating the zone Table.
2020-08-24 22:18:07 - Importing Migration SQL View File to Database, This could take few minuts.
2020-08-24 22:18:08 - DataBase Views File /var/www/MySQL_Database/migrate_controller_view.sql Imported Successfully
2020-08-24 22:18:08 - DataBase Updated Successfully
root@pihome:/var/www/MySQL_Database#
```

**Comment by twa127** [comment]
When I initially did the migration of the database to separate out the zone_sensors table, the field max_operating_time was moved from the zone table to the new zone_sensors table, I've since moved it back to the zone table as it made more sense to leave it there. I updated migrate_db.php, but unless you restored to the pre-updated database and re-ran migrate_db,php you would have max_operation_time still in the zone_sensors table and this would cause the failure of the view update in migrate_controller.php. The failure of the data migration was caused by a typo in migrate_controller.php, the new version fixes both problems and should work with max_operating_time in either the zone table or the zone_sensors table and the result will be that zone, zone_sensors and zone_controllers tables are updated to the latest configuration.

**Comment by twa127** [comment]
I've now updated my live system, so I'll let you know how it goes

**Comment by twa127** [comment]
Setup a Lamp zone with 1 MySensor and 2 Tasmota controllers attached, all seams okay at the moment I can schedule, start from the GUI or voice command them as group. I'll keep you updated

![zone4](https://user-images.githubusercontent.com/46624596/91346888-65cbdc80-e7d9-11ea-821f-2f93a5f83207.JPG)

**Comment by pihome-shc** [comment]
@twa127  That looks very good. How about backend?

**Comment by twa127** [comment]
I now have a working boiler.php, will convert it back from BB to RPi and post a copy

**Comment by twa127** [comment]
okay RPi boiler.php attached, if you execute with a parameter (anything will do) it runs with debug messages eg php boiler.php debug

[boiler.zip](https://github.com/pihome-shc/pihome/files/5132690/boiler.zip)

**Comment by pihome-shc** [comment]
i think i have problem with migrate_controller.php it says all ok but zone controller table is empty,

**Comment by pihome-shc** [comment]
spoke to soon, i just replicated my live database to dev and did update. and then migrate controller and all worked and boiler.php is working as  well.

**Comment by twa127** [comment]
please let me know if you find any problems

**Comment by scottagecheeseandcrackers** [comment]
@twa127 / @pihome-shc  - I understand the great work you have set out above was primarily aimed at simultaneous control of multiple sonoff lights. Is there a way that this process could also be used for heating zones? Ie. if you have multiple zones simply measuring temperature in different rooms but these are all grouped under one zone valve (eg. ground floor) - that any one of the individual rooms could be a controller for the group?

**Comment by twa127** [comment]
thinking out loud -

1. Yes could work
2. Would need to identify the active controller some how, perhaps in the nodes table, but that might be difficult for GPIO controllers, or f we used the zone_controllers table, we would need to identify the active controller in the add/edit zone screen
3. Would need some sort of simple way to swap the active controller without having to edit the zone

**Comment by twa127** [comment]
Perhaps we should not have all these dummy zones which are really only used to display room temperatures. We could display the dummy zones as controllers perhaps to the right of the boiler tile and be able to swap the active zone controller for the 'real' zones (which we can do anyway from the zones GUI).

**Comment by pihome-shc** [comment]
@twa127 are you finished with testing multi controller?

**Comment by twa127** [comment]
I've been using on my live system for a couple of weeks and all appears okay. Not yet done anything with the dummy zones, apart from thinking that it sounds like a good idea :-)

tested the data migration with @scottagecheeseandcrackers  last database post and all worked okay. It might be a good idea if I commit without the database changes initially, this way the database will not get changed before running the data migration and avoid screwing up the existing database. What do you think ?

**Comment by pihome-shc** [comment]
yes, leaving database for next round is good idea, do you need me to test anything or you can do pull request for this.

**Comment by twa127** [comment]
I've been running this version live for over a week so think it is good to go, I'll commit the the update later today

**Comment by pihome-shc** [comment]
@twa127 anything else left to work on this issue?

**Comment by pihome-shc** [comment]
have small issue, i created zone and then deleted it, it got purge 1 but zone is still there, i think cron/piconnect.php need some modifications to delete zone.

**Comment by twa127** [comment]
I'll investigate

**Comment by pihome-shc** [comment]
received email from one PiHome user. 

Hi
In general, after the reinstalling all works, however there are some issues
1) In zone setup, there are 2 records of every zone sensor; it was only one at the beginning but when I corrected the names of every zone because of incorrect LV characters, double record has been created
![image](https://user-images.githubusercontent.com/33334232/93518764-2fd7cf00-f925-11ea-8bcd-9cfeda3d8709.png)


Probably related issue – there are double zone names also in charts
 
![image](https://user-images.githubusercontent.com/33334232/93518801-3c5c2780-f925-11ea-90d2-8fe8f8a1c0a4.png)

2)	When I press on ‘hot water’ button, nothing opens; despite when hit on other buttons, the schedule opens
![image](https://user-images.githubusercontent.com/33334232/93518821-454cf900-f925-11ea-914a-0673ab43a20c.png)

 

3)	When I’m trying to adjust the hot water temperature of existing schedule, before touching the temperature slidebar, it shows 50 degrees and slidebar is on maximum right position, but when I’m trying to increase/decrease the temperature, the maximum value that can be set is 30 degrees 
![image](https://user-images.githubusercontent.com/33334232/93518845-50a02480-f925-11ea-9079-ce6bc1636fb6.png)

 
![image](https://user-images.githubusercontent.com/33334232/93518860-56960580-f925-11ea-951c-a96585f96718.png)


Do you have any idea about how to prevent those behaviors?

Thank you!

**Comment by twa127** [comment]
I'm guessing that something has gone wrong with the migration process, can you post a copy of the database please

**Comment by pihome-shc** [comment]
Migration worked ok but this issue is after editing zone

**Comment by twa127** [comment]
Okay so all looked okay after migration, then a zone was edited and we ended up with errors. 

How was the zone edited, ie what was changed ?

**Comment by pihome-shc** [comment]
user only changed the name of zone.  
1)	In zone setup, there are 2 records of every zone sensor; it was only one at the beginning but when I corrected the names of every zone because of incorrect LV characters, double record has been created

**Comment by twa127** [comment]
okay, I'll have to backout my latest developments to investigate

**Comment by twa127** [comment]
Managed to reproduce the error, I'll investigate

**Comment by twa127** [comment]
Committed a fix, please let me know if this resolves the issue

**Comment by uldjan** [comment]
I have upgraded the PiHome by using commands
cd /var/www/
git pull origin
However all 3 of the reported issues still persists. Here is a backup:
[pihome_mysql_2020-09-22_22-12-25.zip](https://github.com/pihome-shc/pihome/files/5263563/pihome_mysql_2020-09-22_22-12-25.zip)

**Comment by twa127** [comment]
Can you please post a copy of your database from before the update

**Comment by twa127** [comment]
The zone_sensors table is causing some of your problems
![sensor15](https://user-images.githubusercontent.com/46624596/93983615-b43dae00-fd7a-11ea-825e-64a1ffc24254.JPG)

As you can see there are duplicate entries for zone_id 33,34 and 35, please try deleting id 33, 34 and 35 or 38, 39 and 40 depending which ones have the correct value for sp_deadband

**Comment by uldjan** [comment]
Hi @twa127 
I have deleted the id's 38, 39 and 40. Issues 1 and 2 then resolved. Thank you very much for your advice!
However, the issue 3 still persists.

**Comment by twa127** [comment]
Hi,

The problem is in table zone_type, where id=3 type value should be Water and not Hot Water
![sensor16](https://user-images.githubusercontent.com/46624596/94062082-2693aa00-fdde-11ea-8f75-8bbf99e325ad.JPG)

**Comment by twa127** [comment]
Hi Waseem,


Installing the application and database on the Orange Pi One was not too stressful, the hardware interface will require some work as GPIO python will need to be changed, same with UART. Also the pin header is rotated 180 degrees, so the hat would need modifying.


Setting up the WiFi is very easy as Armbian has a nice command line 'nmtui-connect' which allows selection by SSID


regards


terry

________________________________

**Comment by twa127** [comment]
opps sorry wrong recipient

________________________________

**Comment by uldjan** [comment]
Hi @twa127,
Zone type change resolved the issue.
Thank you very much!

**Comment by uldjan** [comment]
@twa127 
I'm not sure if this is the right place for this issue...  when I look on the temperature graphs of last 24 hours, the time zone on x axis is not the same with time for the drawn chart. Can you suggest where to set the time zone for the x axis?
Thanks!
![Ekrānuzņēmums 2020-09-24 224453](https://user-images.githubusercontent.com/71520325/94193044-7e9edf00-feb8-11ea-81cf-2e6d0ff7539d.png)

**Comment by pihome-shc** [comment]
@uldjan 
Shaun Jepson commented on following post while back, can you try this, file name is changed to chart_load.php 

http://www.pihome.eu/2020/05/24/pihome-version-1-75/

Comment: 
Hello Kevin,

I note that the time axis of all the charts shows up in UTC time. This is not a big issue for you based near Dublin as for six months of the year you are on UTC and the other 6 months just one hour difference. Here in France we are two hours different and it is noticeable.

I have made the following changes to correct this and show the time axis in local time.

update chartfooter.php line 109 from
    xaxis: { mode: "time", timeformat: "%H:%M"}, to
    xaxis: { mode: "time", timezone: "browser", timeformat: "%H:%M"},


update chartfooter.php line 218 from
    xaxis: { mode: "time", timeformat: "%H:%M"}, to
    xaxis: { mode: "time", timezone: "browser", timeformat: "%H:%M"},

update chartfooter.php line 184 from
    xaxis: { mode: "time", timeformat: "%H:%M"},
to	
    xaxis: { mode: "time", timezone: "browser", timeformat: "%H:%M"},
 
Hope this helps with some of the other users in Latvia and Romania who have an even bigger time difference.

Thank You
Shaun Jepson

**Comment by twa127** [comment]
Hi,

The line numbers to change in chart_load.php are 135, 148 and 159

**Comment by uldjan** [comment]
Hi @pihome-shc , @twa127 
The issue with time zone of x-axis resolved!
Thank you very much!

**Comment by uldjan** [comment]
Hi @pihome-shc 
On current lv.php was missing 52 records compared to en.php.
I have added and translated them. Please include it in new installations, otherwise selecting the Latvian language will lose the dashboard and get the notice "This page isn’t working".

[lv.zip](https://github.com/pihome-shc/pihome/files/5285379/lv.zip)

**Comment by pihome-shc** [comment]
@uldjan thank you,

**Comment by pihome-shc** [comment]
@twa127 
your recent change added extra } 
i m getting error on migrate controller

```
root@pihome:/var/www/MySQL_Database# php migrate_controller.php
PHP Parse error:  syntax error, unexpected '}', expecting end of file in /var/www/MySQL_Database/migrate_controller.php on line 182
root@pihome:/var/www/MySQL_Database# php migrate_controller.php

```
